### ISSUE TITLE
HTTP 500 when GET accesss /keymgmt

### ISSUE THREAD

**Issue by videlanicolas** [videlanicolas/assimilator#12]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/var/www/assimilator/app/modules/apikeymgmt.py", line 29, in decorated
    return f(*args, **kwargs)
  File "/var/www/assimilator/app/modules/apikeymgmt.py", line 43, in get
    return apikeys
UnboundLocalError: local variable 'apikeys' referenced before assignment

**Comment by videlanicolas** [comment]
Solved.
